"""
Data integrity and leakage prevention tests.
Auto-generated by AI Research Factory. Adapt to your project.
"""
import json
import os

import pytest
import torch

from src.models.autoencoder import Autoencoder


class TestNoFutureDataLeakage:
    """Ensure no future data leaks into features or training."""

    def test_no_future_timestamps_in_data(self):
        """Data files should not contain dates beyond today."""
        # TODO: Load your dataset and check max date
        # Implement when data pipeline is ready (Phase 2)
        pass

    def test_features_use_past_data_only(self):
        """At time t, features should only use data from t-1 or earlier."""
        # TODO: Verify feature generation respects temporal ordering
        # Implement when feature engineering is ready
        pass

    def test_scaler_fit_on_train_only(self):
        """Scalers/normalizers must be fit on training data only."""
        # TODO: Check that scaler.fit() is called on train split only
        # Implement when preprocessing is ready
        pass

    def test_no_centered_rolling_windows(self):
        """Rolling calculations must use backward-looking windows only."""
        # TODO: Check rolling window parameters
        # Implement when feature engineering is ready
        pass


class TestTrainTestBoundary:
    """Ensure strict temporal separation between train and test."""

    def test_train_test_no_overlap(self):
        """Train and test periods must not overlap."""
        # TODO: Define your split dates and verify no overlap
        # Implement when split logic is ready
        pass

    def test_walk_forward_boundaries(self):
        """Each walk-forward fold must have strictly separated boundaries."""
        # TODO: Verify walk-forward splits
        # Implement when WF is ready
        pass


class TestReportConsistency:
    """Ensure reported metrics match actual computed values."""

    def test_metrics_json_exists(self):
        """metrics.json must exist after each cycle."""
        assert os.path.exists("reports/cycle_1/metrics.json")

    def test_metrics_schema_valid(self):
        """metrics.json must contain required fields."""
        with open("reports/cycle_1/metrics.json") as f:
            metrics = json.load(f)
        required = [
            "sharpeRatio", "annualReturn", "maxDrawdown", "hitRate",
            "totalTrades", "transactionCosts", "walkForward",
        ]
        for field in required:
            assert field in metrics, f"Missing: {field}"

    def test_loss_log_exists(self):
        """loss_log.json must exist and contain epoch entries."""
        with open("reports/cycle_1/loss_log.json") as f:
            log = json.load(f)
        assert len(log) == 10
        for epoch in range(1, 11):
            assert str(epoch) in log


class TestAutoencoderModel:
    """Validate autoencoder architecture and training."""

    def test_autoencoder_forward_shape(self):
        """Output shape must match input shape."""
        model = Autoencoder(input_dim=256, hidden_dim=128, latent_dim=32)
        x = torch.rand(16, 256)
        out = model(x)
        assert out.shape == x.shape

    def test_autoencoder_encode_shape(self):
        """Encoded output must have latent_dim dimensions."""
        model = Autoencoder(input_dim=256, hidden_dim=128, latent_dim=32)
        x = torch.rand(16, 256)
        z = model.encode(x)
        assert z.shape == (16, 32)

    def test_training_reduces_loss(self):
        """A few epochs of training should reduce reconstruction loss."""
        torch.manual_seed(0)
        model = Autoencoder(input_dim=64, hidden_dim=32, latent_dim=8)
        data = torch.rand(100, 64)
        criterion = torch.nn.MSELoss()
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

        initial_loss = criterion(model(data), data).item()
        for _ in range(50):
            optimizer.zero_grad()
            loss = criterion(model(data), data)
            loss.backward()
            optimizer.step()
        final_loss = criterion(model(data), data).item()

        assert final_loss < initial_loss
