"""
Data integrity and leakage prevention tests.
Auto-generated by AI Research Factory. Adapt to your project.
"""
import json
import os
from datetime import datetime

import pytest
import pandas as pd
import torch

from src.models.autoencoder import Autoencoder


RETURNS_PATH = "data/processed/sp100_daily_returns.csv"


class TestNoFutureDataLeakage:
    """Ensure no future data leaks into features or training."""

    def test_no_future_timestamps_in_data(self):
        """Data files should not contain dates beyond the configured end_date."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        end_date = pd.Timestamp("2023-12-31")
        assert df.index.max() <= end_date, (
            f"Data contains dates after {end_date}: max={df.index.max()}"
        )

    def test_no_dates_in_future(self):
        """Data files should not contain dates beyond today."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        today = pd.Timestamp(datetime.now().date())
        assert df.index.max() <= today, (
            f"Data contains future dates: max={df.index.max()}"
        )

    def test_features_use_past_data_only(self):
        """Daily returns use pct_change (t-1 to t), which is backward-looking."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        # Returns should be reasonable (no look-ahead artifacts)
        assert df.abs().max().max() < 1.0, "Suspicious return > 100%"

    def test_no_bfill_phantom_returns(self):
        """Pre-IPO periods must not have constant non-zero returns from bfill."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        # Check annualized return for each stock — no stock should exceed 200%/yr
        ann_ret = df.mean() * 252
        assert ann_ret.max() < 2.0, (
            f"Suspicious annualized return > 200%: "
            f"{ann_ret.idxmax()} = {ann_ret.max():.2f}"
        )

    def test_scaler_fit_on_train_only(self):
        """Scalers/normalizers must be fit on training data only."""
        # N/A for Phase 2 — no scaler used yet
        pass

    def test_no_centered_rolling_windows(self):
        """Rolling calculations must use backward-looking windows only."""
        # N/A for Phase 2 — no rolling windows used
        pass


class TestDataQuality:
    """Validate the generated returns dataset."""

    def test_returns_file_exists(self):
        """sp100_daily_returns.csv must exist."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        assert os.path.exists(RETURNS_PATH)

    def test_no_nan_values(self):
        """Returns data must have no NaN values."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        assert df.isna().sum().sum() == 0, f"Found NaN values in returns data"

    def test_minimum_assets(self):
        """Must have at least 80 assets."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        assert df.shape[1] >= 80, f"Only {df.shape[1]} assets, need >= 80"

    def test_minimum_rows(self):
        """Must have at least 3000 data rows."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        assert df.shape[0] >= 3000, f"Only {df.shape[0]} rows, need >= 3000"

    def test_date_range(self):
        """Data should span from 2010 to 2023."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        df = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        assert df.index.min().year == 2010
        assert df.index.max().year == 2023


class TestTrainTestBoundary:
    """Ensure strict temporal separation between train and test."""

    def test_train_test_no_overlap(self):
        """Train and test periods must not overlap in walk-forward windows."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        from src.evaluation.framework import WalkForwardValidator

        returns = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        validator = WalkForwardValidator(returns, train_months=60, test_months=1)
        windows = validator._generate_windows()

        assert len(windows) > 0, "No walk-forward windows generated"

        for train_start, test_start, test_end in windows:
            # Train period must end strictly before test period begins
            assert train_start < test_start, (
                f"Train start {train_start} not before test start {test_start}"
            )
            assert test_start < test_end, (
                f"Test start {test_start} not before test end {test_end}"
            )

    def test_walk_forward_boundaries(self):
        """Each walk-forward fold must have strictly separated boundaries."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        from src.evaluation.framework import WalkForwardValidator

        returns = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        validator = WalkForwardValidator(returns, train_months=60, test_months=1)
        windows = validator._generate_windows()

        assert len(windows) >= 5, f"Only {len(windows)} windows, need >= 5"

        for i, (train_start, test_start, test_end) in enumerate(windows):
            train_data = returns.loc[train_start:test_start - pd.Timedelta(days=1)]
            test_data = returns.loc[test_start:test_end - pd.Timedelta(days=1)]

            # No overlap between train and test indices
            overlap = train_data.index.intersection(test_data.index)
            assert len(overlap) == 0, (
                f"Window {i}: train/test overlap on {len(overlap)} dates"
            )

    def test_no_forward_looking_in_weights(self):
        """Strategy weights must be computed from training data only."""
        if not os.path.exists(RETURNS_PATH):
            pytest.skip("Returns data not yet generated")
        import numpy as np
        from src.evaluation.framework import WalkForwardValidator
        from src.strategies.benchmarks import EqualWeightStrategy

        returns = pd.read_csv(RETURNS_PATH, index_col=0, parse_dates=True)
        validator = WalkForwardValidator(returns, train_months=60, test_months=1)
        result = validator.run(EqualWeightStrategy())

        # Weights history should exist and have entries
        assert len(result["weights_history"]) > 0
        # Each weight vector should sum to ~1
        for date, weights in result["weights_history"]:
            assert abs(np.sum(weights) - 1.0) < 1e-6, (
                f"Weights at {date} sum to {np.sum(weights)}, not 1.0"
            )


class TestReportConsistency:
    """Ensure reported metrics match actual computed values."""

    def test_metrics_json_exists(self):
        """metrics.json must exist after each cycle."""
        assert os.path.exists("reports/cycle_4/metrics.json")

    def test_metrics_schema_valid(self):
        """metrics.json must contain required fields."""
        with open("reports/cycle_4/metrics.json") as f:
            metrics = json.load(f)
        required = [
            "sharpeRatio", "annualReturn", "maxDrawdown", "hitRate",
            "totalTrades", "transactionCosts", "walkForward",
        ]
        for field in required:
            assert field in metrics, f"Missing: {field}"

    def test_walk_forward_windows_sufficient(self):
        """Walk-forward must have at least 5 windows."""
        with open("reports/cycle_4/metrics.json") as f:
            metrics = json.load(f)
        assert metrics["walkForward"]["windows"] >= 5, (
            f"Only {metrics['walkForward']['windows']} windows, need >= 5"
        )

    def test_benchmark_returns_json_exists(self):
        """benchmark_returns.json must exist with required keys."""
        path = "reports/cycle_4/benchmark_returns.json"
        assert os.path.exists(path), f"{path} not found"
        with open(path) as f:
            data = json.load(f)
        assert "equal_weight" in data, "Missing 'equal_weight' key"
        assert "min_variance" in data, "Missing 'min_variance' key"
        assert "deep_portfolio" in data, "Missing 'deep_portfolio' key"
        assert len(data["equal_weight"]["daily_returns"]) > 0
        assert len(data["min_variance"]["daily_returns"]) > 0
        assert len(data["deep_portfolio"]["daily_returns"]) > 0

    def test_deep_portfolio_metrics_in_custom(self):
        """metrics.json customMetrics must contain Deep Portfolio results."""
        with open("reports/cycle_4/metrics.json") as f:
            metrics = json.load(f)
        custom = metrics["customMetrics"]
        assert "deep_portfolio_sharpe" in custom
        assert "baseline_1n_sharpe" in custom
        assert "strategy_vs_1n_sharpe_diff" in custom

    def test_deep_portfolio_ae_returns_exists(self):
        """deep_portfolio_ae_returns.json must exist with return data."""
        path = "reports/cycle_4/deep_portfolio_ae_returns.json"
        assert os.path.exists(path), f"{path} not found"
        with open(path) as f:
            data = json.load(f)
        assert "daily_returns" in data
        assert len(data["daily_returns"]) > 0
        assert data["strategy"] == "deep_portfolio_ae"


class TestDeepPortfolioStrategy:
    """Validate the Deep Portfolio strategy."""

    def test_generates_valid_weights(self):
        """Deep Portfolio must produce weights that sum to 1 and are non-negative."""
        import numpy as np
        from src.strategies.deep_portfolio import DeepPortfolioStrategy

        # Small synthetic returns for testing
        np.random.seed(42)
        dates = pd.date_range("2020-01-01", periods=100, freq="B")
        returns = pd.DataFrame(
            np.random.randn(100, 10) * 0.01,
            index=dates,
            columns=[f"A{i}" for i in range(10)],
        )

        strategy = DeepPortfolioStrategy(
            hidden_dim=16, latent_dim=4, epochs=10, seed=42,
        )
        weights = strategy.generate_weights(returns)

        assert len(weights) == 10
        assert abs(np.sum(weights) - 1.0) < 1e-6
        assert np.all(weights >= 0)

    def test_uses_only_training_data(self):
        """Weights must change when training data changes."""
        import numpy as np
        from src.strategies.deep_portfolio import DeepPortfolioStrategy

        np.random.seed(42)
        dates = pd.date_range("2020-01-01", periods=200, freq="B")
        # Use higher variance and distinct patterns for the two halves
        r1 = np.random.randn(100, 10) * 0.01
        r2 = np.random.randn(100, 10) * 0.05 + 0.01
        data = np.vstack([r1, r2])
        returns = pd.DataFrame(
            data,
            index=dates,
            columns=[f"A{i}" for i in range(10)],
        )

        strategy = DeepPortfolioStrategy(
            hidden_dim=16, latent_dim=4, epochs=50, seed=42,
        )
        w1 = strategy.generate_weights(returns.iloc[:100])
        w2 = strategy.generate_weights(returns.iloc[100:])

        # Weights should differ for different data (looser tolerance)
        assert not np.allclose(w1, w2, atol=1e-3)


class TestAutoencoderModel:
    """Validate autoencoder architecture and training."""

    def test_autoencoder_forward_shape(self):
        """Output shape must match input shape."""
        model = Autoencoder(input_dim=256, hidden_dim=128, latent_dim=32)
        x = torch.rand(16, 256)
        out = model(x)
        assert out.shape == x.shape

    def test_autoencoder_encode_shape(self):
        """Encoded output must have latent_dim dimensions."""
        model = Autoencoder(input_dim=256, hidden_dim=128, latent_dim=32)
        x = torch.rand(16, 256)
        z = model.encode(x)
        assert z.shape == (16, 32)

    def test_training_reduces_loss(self):
        """A few epochs of training should reduce reconstruction loss."""
        torch.manual_seed(0)
        model = Autoencoder(input_dim=64, hidden_dim=32, latent_dim=8)
        data = torch.rand(100, 64)
        criterion = torch.nn.MSELoss()
        optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

        initial_loss = criterion(model(data), data).item()
        for _ in range(50):
            optimizer.zero_grad()
            loss = criterion(model(data), data)
            loss.backward()
            optimizer.step()
        final_loss = criterion(model(data), data).item()

        assert final_loss < initial_loss
